export const GET_ALL_PRODUCT_API = 'GET_ALL_PRODUCT_API';
export const CREATE_PRODUCT_API = 'CREATE_PRODUCT_API'
export const UPDATE_PRODUCT_API = 'UPDATE_PRODUCT_API'
export const DELETE_PRODUCT_API = 'DELETE_PRODUCT_API'
export const BUY_PRODUCT_PRODUCT_API = 'BUY_PRODUCT_PRODUCT_API'